let RESOLUTION_SCALE_DOWN = 1;
let h = window.innerHeight / RESOLUTION_SCALE_DOWN;
let w = window.innerWidth / RESOLUTION_SCALE_DOWN;
const scene = new THREE.Scene();
const renderer = new THREE.WebGLRenderer();
renderer.setSize(w, h);
renderer.domElement.style.width = "100%";
renderer.domElement.style.height = "100%";
const container = document.querySelector("div#canvas-container");
container.appendChild(renderer.domElement);
